### ISSUE TITLE
EPUB navigator does not work on Android 6 (API <= 23)

### ISSUE THREAD

**Issue by dotmonkey** [readium/r2-navigator-kotlin#127] opened 2020-05-08 03:23 UTC
open any epub file the epub webview has layout errors(no margin) 

**webview console error info:**
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by twaddington** [comment] 2020-05-08 15:47
This is an issue with `utils.js`, which has some syntax issues. We patched this locally at NYPL but forgot to merge it upstream.

If I remember right it's the update function using `let` and also missing a semi-colon.

https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/assets/scripts/utils.js#L16-L19

**Comment by twaddington** [comment] 2020-05-08 15:51
I can get a patch ready today.

**Comment by mickael-menu** [comment] 2020-05-13 15:42
@twaddington Thanks for chiming in on this issue, do you think you might able to send a PR soon?

**Comment by twaddington** [comment] 2020-05-13 15:48
@mickael-menu yep! Got distracted by something else. I can work on this today.

**Comment by twaddington** [comment] 2020-05-14 07:02
@mickael-menu didn't get this finished today but will take care of it first thing tomorrow.

**Comment by munnadroid** [comment] 2020-08-30 08:11
Any update on this issue?

**Comment by mickael-menu** [comment] 2020-08-31 06:39
@munnadroid No update so far. Would you care trying to change the `let` to `var` and opening a PR if it fixes the problem for you?

**Comment by munnadroid** [comment] 2020-08-31 06:51
I changed highlight.js and utils.js to ES5, the error is not in the console now but still, the reader is not able to render the ebook correctly, cannot change appearance mode, size, etc.

**Comment by mickael-menu** [comment] 2020-08-31 07:05
Okay, looks like the problem is deeper... I'll take a look in case I see anything quickly, but I won't be able to spend much time on this issue at the moment, unfortunately. Would you mind sharing your updated JS files?

**Comment by munnadroid** [comment] 2020-09-01 15:36
Sure, I will send PR of es5 js.

**Comment by mickael-menu** [comment] 2021-01-20 12:03
`utils.js` doesn't use ES6 features anymore, but even after removing `highlight.js`, the pagination was still broken.

Unfortunately [the Chrome inspector is completely broken](https://groups.google.com/g/google-chrome-developer-tools/c/s47cbyLKvxA) and I can't find an older version of Chromium which works. This makes it very difficult to debug this issue.

**Comment by JayPanoz** [comment] 2021-01-20 13:28
> I can't find an older version of Chromium which works.

If someone has time to waste, [all the chromium snapshots can be found here](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html). You have to know the Chromium build number you'd like to use tho.

**Comment by HadrienGardeur** [comment] 2021-01-20 13:49
Since the embedded webviiew can be updated through the Play Store on Android, is this really something that we should test at all?

**Comment by mickael-menu** [comment] 2021-01-20 14:09
@JayPanoz Yes that's where I tried to find a version of Chromium that worked but the `chrome://inspect` page always crashed.

@HadrienGardeur Many seem to encounter this issue though.

**Comment by mickael-menu** [comment] 2021-01-20 17:40
So after some clarifications in the weekly meeting, people *should* be able to install the Chromium web view in 21+, which is required to run Readium CSS (and so pagination).

We need:

* to check on a device if after installing the web view, it works on 21+ (cc @aferditamuriqi ?)
* have a runtime check to prevent running the EPUB navigator if the Chromium web view is not available (and up to date)

**Comment by twaddington** [comment] 2021-02-03 19:34
Sorry, I never got around to following up on this. I don't have an exact patch to address this issue, but here is a copy of our `utils.js` after we resolved the issue. I believe it was related to the use of `let` declarations and some function expressions.

https://gist.github.com/twaddington/30833457d312082af0b40d2deef68ab4

**Comment by m-ochyra** [comment] 2021-04-20 10:57
I converted hightlight.js syntax to ES5 using babel online tool, but problem with working on older devices still exists.

And I found a reason. The next issue is using variables in CSS which are not valid in old WebView.

Take a look at my screenshot from DevTools from Android 5.1:
![image](https://user-images.githubusercontent.com/5583015/115384999-ef507480-a1d7-11eb-84ca-1983cfb2a458.png)

**Comment by mickael-menu** [comment] 2021-04-20 11:53
@m-ochyra Have you tried after installing the [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US) on your device?

It is unlikely we will modify Readium CSS to support these old devices, but installing an updated WebView should be a workaround.

**Comment by JayPanoz** [comment] 2021-04-20 11:58
@mickael-menu Yeah no it was outscoped from the very start indeed because it was too much burden. 

We even had an issue for discussing the best way to handle non-support here: https://github.com/readium/readium-css/issues/14

**Comment by m-ochyra** [comment] 2021-04-20 12:00
@mickael-menu Yes, I already tried to run app on device with Android 6.0.1 and newer version of WebView and reader works very well.

I can't check on Android 5 device, because I don't have any and on Android 5 emulator installing new version of WebView doesn't resolve issue.

**Comment by mickael-menu** [comment] 2021-04-20 12:02
> @mickael-menu Yes, I already tried to run app on device with Android 6.0.1 and newer version of WebView and reader works very well.

Thanks for the feedback, that's good to know that it solves the issue on Android 6.

> I can't check on Android 5 device, because I don't have any and on Android 5 emulator installing new version of WebView doesn't resolve issue.

I don't have any either. Hopefully another contributor will be able to try this out on a real device.

**Comment by mickael-menu** [comment] 2022-07-29 13:28
Should be fixed by now.

**Closed by mickael-menu** 2022-07-29 13:28 UTC
Labels: bug, help wanted
